apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: my-springboot-app
spec:
  replicas: 1
  selector:
    app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
        - name: my-springboot-app
          image: your-springboot-image:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: Lamp054
