apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: Consuming-Apirest-Java-Deploy
spec:
  replicas: 1
  selector:
    app: Consuming-Apirest-Java-Deploy
  template:
    metadata:
      labels:
        app: Consuming-Apirest-Java-Deploy
    spec:
      containers:
        - name: Consuming-Apirest-Java-Deploy
          image: Consuming-Apirest-Java-Deploy:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
