apiVersion: v1
kind: Template
metadata:
  name: Consuming-Apirest-Java-Deploy
objects:
  - kind: ImageStream
    metadata:
      name: Consuming-Apirest-Java-Deploy
  - kind: DeploymentConfig
    metadata:
      name: Consuming-Apirest-Java-Deploy
    spec:
      replicas: 1 
      template:
        metadata:
          labels:
            app: Consuming-Apirest-Java-Deploy
        spec:
          containers:
            - name: Consuming-Apirest-Java-Deploy
              image: Consuming-Apirest-Java-Deploy:latest 
              ports:
                - containerPort: 8082
  - kind: Service
    metadata:
      name: Consuming-Apirest-Java-Deploy
    spec:
      ports:
        - name: 8082-tcp
          port: 8082
          targetPort: 8082
      selector:
        app: Consuming-Apirest-Java-Deploy
