apiVersion: v1
kind: Template
metadata:
  name: spring-boot-app-template
objects:
  - kind: ImageStream
    metadata:
      name: spring-boot-app
  - kind: DeploymentConfig
    metadata:
      name: spring-boot-app
    spec:
      replicas: 1 
      template:
        metadata:
          labels:
            app: spring-boot-app
        spec:
          containers:
            - name: spring-boot-app
              image: spring-boot-app:latest 
              ports:
                - containerPort: 8080
  - kind: Service
    metadata:
      name: spring-boot-app
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: 8080
      selector:
        app: spring-boot-app
