version: '3'
services:
  spring-boot-app:
    image: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      PORT=8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Lamp054

  postgres:
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile-db  
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lamp054
    ports:
      - "5432:5432"


