version: '3'
services:
  spring-boot-app:
    image: Consuming-Apirest-Java-Deploy:latest
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  postgres:
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile-db  
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"


